language: python
sudo: required
dist: xenial
python:
#  - "2.6"
#  - "2.7"
#  - "3.3"
#  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
# command to install dependencies
before_install:
  # Install pre-trained models
  - wget https://github.com/OlafenwaMoses/ImageAI/releases/download/1.0/yolo.h5
install:
  # Install python packages
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-black
  - pip install mypy
before_script:
- export DISPLAY=:99.0
script:
  - mypy . --ignore-missing-imports
  - xvfb-run -a pytest -vs --black
